### DISCUSSION TITLE
Restructuring the Codebase for GraphQL Schema Generation

### DISCUSSION THREAD

**Discussion by danbi2990** [aicers/giganto#1099] [General]
This discussion continues from this [PR](https://github.com/aicers/giganto/pull/1043#issuecomment-2910931528).

@sehkone 

> Could you create a discussion post while closing this PR to follow up on the context? Personally, I think giganto and giganto-proc-macro would be better.

`giganto` is the binary built by the workspace as follows:
```toml
# ...
[workspace]
members = ["giganto-system", "giganto-proc-macro"]

[package]
name = "giganto-runner"
version.workspace = true
edition.workspace = true

[[bin]]
name = "giganto"
# ...
```
For brevity, this detail was previously omitted, but the codebase actually contains three packages:

- `giganto-runner`: the main binary
- `giganto-system`: a library crate
- `giganto-proc-macro`: a procedural macro crate

> Is it possible for build.rs to detect changes in the graphql module?

It's possible to detect changes in the `graphql` module. However, since the `graphql` module is part of `giganto-system`, which is treated as an external dependency, this makes change detection ineffective. Any change in `giganto-system` will trigger a rebuild, regardless of whether the `graphql` files were modified.

To resolve this issue, the graphql module would need to be moved into the main package. However, doing so prevents it from being used in `[build dependencies]` which is necessary for calling its functions from `build.rs`.
