### ISSUE TITLE
Enforce Markdown Linting in CI

### ISSUE THREAD

**Issue by henry0715-dev** [aicers/giganto#1091]
To ensure consistency and quality of Markdown files across all repositories, we will enforce markdown linting as part of the CI workflow.

### Steps

1. **Add a `.markdownlint.yaml` configuration file**  
   The minimum required configuration is:

   ```yaml
   ---
   MD024:
     siblings_only: true
   ```

2. **Update CI workflows to include a markdown lint check**  
   A new job should be added to the CI configuration as follows:

   ```yaml
   jobs:
     check:
       runs-on: ...
       steps:

         ...

         - name: markdownlint
           run: markdownlint *.md

         ...
   ```
